### ISSUE TITLE
Bigtimer version 2.1.4

### ISSUE THREAD

**Issue by SNoof85** [hassio-addons/addon-node-red#128]
# Problem/Motivation

> Bigtimer still 2.1.4 and make nodered addon failed to start. I disabled the flow using bigtimer and nodered started. Then i've deleted all bigtimer nodes. Deployed. Uninstall addon and reinstall. In manage palette i still have bigtimer 2.1.4. And if i add a bigtimer node, the deploy will make nodered crash with some error from bigtimer.

## Expected behavior

> Should start with bigtimer 2.1.5

## Actual behavior

> Still 2.1.4 version even after uninstall/reinstall addon

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by firestrife23** [comment]
confirmed, having same issue.... all of my automation is broken because of this.

**Comment by aav7fl** [comment]
I took a look at the last stable Node-RED release from my snapshots and found that I was using BigTimer `1.0.9` (https://github.com/hassio-addons/addon-node-red/pull/116). While it may work for newer versions, I decided to force an install of that older version and have it working.

On the Home Assistant add-on config for Node-RED, I added the following config to force that install:

```yaml
  "npm_packages": [
    "node-red-contrib-bigtimer@2.0.9"
  ],
```

**Comment by dorbak** [comment]
l

> I took a look at the last stable Node-RED release from my snapshots and found that I was using BigTimer `2.0.9` (#116). While it may work for newer versions, I decided to force an install of that older version and have it working.
> 
> On the Home Assistant add-on config for Node-RED, I added the following config to force that install:
> 
> ```yaml
>   "npm_packages": [
>     "node-red-contrib-bigtimer@2.0.9"
>   ],
> ```

That worked for me - thank you @aav7fl

**Comment by SNoof85** [comment]
Well tried with 2.1.5 forced in npm packages and same errors. With 2.0.9 it's working. Means it's not related to the add-on ?

**Comment by aav7fl** [comment]
There's a good chance it's Big Timer. 

Here's a comment on the author's post on the node module where someone had a similar issue as we are having, but it was resolved with 2.1.5.

https://tech.scargill.net/big-timer/#comment-50238

I suppose we can leave a comment on that page linking Scargill to this GitHub issue.

**Comment by Darw1n85** [comment]
@aav7fl the solution you posted didn't work for me. I had to console into node red container and do npm i node-red-contrib-bigtimer@2.0.9 to get it to work. My Intel Nuc almost exploded by the temperatures of restarting node red every 2 seconds. :(
Tried also to force 2.1.5 but something seems to be wrong because it is 2.1.4 still after the installation.

**Comment by 1iveowl** [comment]
> I took a look at the last stable Node-RED release from my snapshots and found that I was using BigTimer `2.0.9` (#116). While it may work for newer versions, I decided to force an install of that older version and have it working.
> 
> On the Home Assistant add-on config for Node-RED, I added the following config to force that install:
> 
> ```yaml
>   "npm_packages": [
>     "node-red-contrib-bigtimer@2.0.9"
>   ],
> ```

Worked for me too. Thank you!

**Comment by tdolder** [comment]
> I took a look at the last stable Node-RED release from my snapshots and found that I was using BigTimer `2.0.9` (#116). While it may work for newer versions, I decided to force an install of that older version and have it working.
> 
> On the Home Assistant add-on config for Node-RED, I added the following config to force that install:
> 
> ```yaml
>   "npm_packages": [
>     "node-red-contrib-bigtimer@2.0.9"
>   ],
> ```

Worked for me too, Thanks!

**Comment by frenck** [comment]
A fix by the author of bigtimer is expected today.
I'm holding off shipping 2.1.5, since that will not fix the issue.

**Comment by trevorjdaniel** [comment]
Apologies, I am running Node-Red on a Raspberry Pi.

Where can i find the file i need to edit please?

I have tried adding the npm_pacakages setting to my settings.js file but it causes an error when starting node-red?

**Comment by trevorjdaniel** [comment]
For me, i ran

npm install node-red-contrib-bigtimer@2.0.9

at the command line and it fixed my problem

**Comment by frenck** [comment]
2.0.9 might cause issues for other users, hence me not publishing a downgrade at this point.
Just hold on a little longer.

**Comment by frenck** [comment]
Fixed in v1.3.1 of the add-on (which ships node-red-contrib-bigtimer@2.1.6)

**Comment by Darw1n85** [comment]
Can confirm it is working great on Intel NUC. Thanks!

**Comment by msauto** [comment]
> Fixed in v1.3.1 of the add-on (which ships node-red-contrib-bigtimer@2.1.6)

sorry i know you closed this but i cant figure out how to force update from 1.3.0 to 1.3.1 in hassio .A Little help please.

**Comment by trevorjdaniel** [comment]
Same here really but for Node-Red... How can i get the upate?

The Palette Manager still shows 2.5.1 as the latest available version?

Any help would be greatly appreciated.

**Comment by msauto** [comment]
> Same here really but for Node-Red... How can i get the upate?
> 
> The Palette Manager still shows 2.1.5 as the latest available version?
> 
> Any help would be greatly appreciated.

yes, i meant for node red addon in hassio. if you are referring node- red addon in hass.io, the version will be at... open hassio in panel on left, then click node-red, the version will be at top right. if 1.3.0 this is old if 1.3.1 it is new and should be fixed.

**Comment by tdolder** [comment]
Update to version 1.3.1 done,  up and running again on my Intel NUC. Thanks!

**Comment by msauto** [comment]
I was actually able to keep clicking on reload to get node red to finally load up. It still would not work but I could edit removed all the bigtimer nodes and disabled bigtime. Restarted homeassistant and all is good still running 1.3.0 can't figure out how to manually force update

**Comment by frenck** [comment]
@msauto in the hassio addon store, too right corner, reload button. Click it, wait 1 minute... upgrade!

**Comment by msauto** [comment]
Thanks Frenck preciate it

**Comment by trevorjdaniel** [comment]
![image](https://user-images.githubusercontent.com/2582681/52596084-5a0f0400-2e47-11e9-9e04-590e6f1a8662.png)

In Node-Red it's still 2.1.5

**Comment by msauto** [comment]
Yes, we are not changing the version number of the program "node red". We are changing the version of the addon in hassio,or at least that's what this thread is about. If you are running node red outside of hassio as an independent program that will require a different upgrade procedure if I'm not mistaken I believe you have to download it it's been a while since I ran it outside of the hassio addon system.

**Comment by msauto** [comment]
I am pretty sure that the incompatibility with big timer is an incompatibility in the addon rather than the actual node-red program itself. But I honestly don't know for positive, I just assumed that since frenck got involved as he is the one that wrote the addon for hassio.

**Comment by Elmardus** [comment]
I have done the update, but I'm still getting some strange behavior from Bigtimer. I am on the new version:
![Bigtimer version](https://user-images.githubusercontent.com/25563589/52603532-7a4ebb00-2e67-11e9-98cb-51d188885035.JPG)

I created the following test flow:

![test flow](https://user-images.githubusercontent.com/25563589/52603545-8c305e00-2e67-11e9-90c4-78fd4819cbc3.JPG)

And even though the label below the timer will say it is 'on' at the right time, no output is sent. The debug node never receives a message, and the light.turn_on service is never getting triggered. Is there anything I can try?

**Comment by msauto** [comment]
Honestly I always had little buggy issues with bigtimer. I don't think it was a problem with the node itself. I think it was with me. But quite frankly it is way more powerful than what I really needed. I simply need sun-up sun-down and simple daily timing node. I achieve that quite easily with the inject node and the time inject node for sunup and sundown. They are both just really quick and simple. That said I do remember having any issues similar to what you are having and I started using the 3rd or bottom output on the Node instead of the top one  is an extra output for speech and debugging. Other than that I would recommend opening another request for help because this is somewhat off of the original subject and you probably won't get too many people helping. you would have better luck from people way smarter than me on it if you open another thread and request help it's changing to the bottom connector doesn't do the job. Not that I don't want to help you I'm just not that sharp still learning myself.Lots of information at this website as well  https://tech.scargill.net/big-timer/

**Comment by Just-another-pleb** [comment]
2.1.1 works.

I had 2.1.3 and it died.

**Comment by frenck** [comment]
I'm going to stop this discussion. Since the discussion is going nowhere, and the add-on has been fixed.

Add-on version 1.3.1 has been released, shipping Node-RED Bigtimer 2.1.7.

If you have any issues with Bigtimer, please feel free to report them on the homepage of Bigtimer.
